### ISSUE TITLE
Suggested feature: Return all countries

### ISSUE THREAD

**Issue by sterichards** [rsertelon/iso-3166-country-codes-angular#18]
Hi,

This would do me excellent if a function was implement to return all country codes.

Ste,

**Comment by rsertelon** [comment]
Hi,

You mean an array of country codes ? such as `['FR', 'EN', ...]` ?

**Comment by sterichards** [comment]
Yes, that would be great.

Thank you

**Comment by rsertelon** [comment]
Will do ASAP ;)

**Comment by thomasmktong** [comment]
I think we can simply use this?
```
ISO3166.codeToCountry
```
