### ISSUE TITLE
publish to npm registry

### ISSUE THREAD

**Issue by ctaepper** [rsertelon/iso-3166-country-codes-angular#20]
In order for best usage of CommonJS module, this should be installable via npm, too... browserify & webpack users try to not use bower anymore

**Comment by rsertelon** [comment]
You speak of CommonJS, is there anything more to do than publishing the package on npm registry?

**Comment by ctaepper** [comment]
no, your module is perfectly prepared:
- set up main in package.json
- point it to index.js
- export the module name in index.js

only thing missing is npm publishing, preferably with a new version including your current HEAD :)

**Comment by rsertelon** [comment]
Right, someone contributed the CommonJS compatibility :)

I will release as soon as #18 is fixed ;) and push to npm registry.

Thanks for the suggestion!

**Comment by SpencerCarstens** [comment]
+1

**Comment by rsertelon** [comment]
@ctaepper @SpencerCarstens It should be available on npm registry. Can you confirm it's OK please?

Thanks!

**Comment by ctaepper** [comment]
confirmed! thank you

**Comment by rsertelon** [comment]
Great ;)
