### ISSUE TITLE
getCountryCode returns undefined

### ISSUE THREAD

**Issue by aalega2** [rsertelon/iso-3166-country-codes-angular#23]
Hi, 

I like the plugin, however everything works except for getCountryCode. Any ideas?

**Comment by rsertelon** [comment]
Hi,

I'll try to look into it this week, no promise ;)

**Comment by TBxy** [comment]
`toUpperCase()` is missing (holder.codeToCountry[key])

    for(var key in holder.codeToCountry) {
      holder.countryToCode[holder.codeToCountry[key].toUpperCase()] = key;
      holder.countryCodes.push(key);
    }
