### ISSUE TITLE
Feature: include TypeScript definitions

### ISSUE THREAD

**Issue by igorlino** [rsertelon/iso-3166-country-codes-angular#28]
Hi,

At the moment is not possible to cleanly integration this angular module with typescript, since there are not types available for it. (for example at:  https://github.com/DefinitelyTyped/DefinitelyTyped)

There is an easy way to do it, if only including the definitions directly as part of the package.

For example moment.js includes them 
https://github.com/moment/moment/blob/develop/moment.d.ts

So something like:

dist/iso-3166-country-codes-angular.d.ts

Thanks.

PS: If you like, I can create them and make a pull request.

**Comment by rsertelon** [comment]
@igorlino Thanks for the issue, I'd love the PR if you could. I'm mostly integrating patches and releasing the software now :)

**Comment by igorlino** [comment]
At least the service is covered, and would already give nice code autocompletion for the country 🥇

**Comment by igorlino** [comment]
if, you like the change, would you be so kind to make a new minor release, so that I can consume it? thanks

**Comment by rsertelon** [comment]
Merged, I'll try to release soon. Ping me if you don't see progress, I might forget about it unwillingly :)
